const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export type Level = "primary" | "middle" | "secondary";

export interface ChatPayload {
  user_id: number;
  message: string;
  level?: Level;
  /** Pass the value from the previous response to continue an existing session. */
  conversation_id?: string;
}

export interface ChatResult {
  response: string;
  /** Echo this back in the next request to keep the same conversation session. */
  conversation_id: string;
  /** Optional assessment quiz generated by the backend. */
  quiz?: {
    question: string;
  };
}

export async function sendMessage(payload: ChatPayload): Promise<ChatResult> {
  const res = await fetch(`${API_BASE}/api/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => res.statusText);
    throw new Error(`API error ${res.status}: ${detail}`);
  }

  return res.json() as Promise<ChatResult>;
}

export interface Conversation {
  id: string;
  user_id: number;
  title: string;
  created_at: string;
}

export interface StoredMessage {
  id: number;
  conversation_id: string;
  role: "user" | "ai";
  content: string;
  created_at: string;
}

export async function getConversations(userId: number, q?: string): Promise<Conversation[]> {
  const url = new URL(`${API_BASE}/api/conversations`);
  url.searchParams.append("user_id", userId.toString());
  if (q) url.searchParams.append("q", q);
  
  const res = await fetch(url.toString());
  if (!res.ok) throw new Error("Failed to fetch conversations");
  return res.json();
}

export async function getMessages(conversationId: string, signal?: AbortSignal): Promise<StoredMessage[]> {
  const res = await fetch(`${API_BASE}/api/messages?conversation_id=${conversationId}`, {
    signal,
  });
  if (!res.ok) throw new Error("Failed to fetch messages");
  return res.json();
}

export async function updateConversationTitle(id: string, title: string) {
  const res = await fetch(`${API_BASE}/api/conversations/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ title }),
  });
  if (!res.ok) throw new Error("Failed to update title");
  return res.json();
}

export async function deleteConversation(id: string) {
  const res = await fetch(`${API_BASE}/api/conversations/${id}`, {
    method: "DELETE",
  });
  if (!res.ok) throw new Error("Failed to delete conversation");
  return res.json();
}

export interface MessageSearchResult {
  conversation_id: string;
  content: string;
  title: string;
}

export async function searchMessages(userId: number, q: string): Promise<MessageSearchResult[]> {
  const url = new URL(`${API_BASE}/api/search/messages`);
  url.searchParams.append("user_id", userId.toString());
  url.searchParams.append("q", q);
  
  const res = await fetch(url.toString());
  if (!res.ok) throw new Error("Failed to search messages");
  return res.json();
}

export interface EvaluatePayload {
  user_id?: number;
  question: string;
  answer: string;
}

export interface EvaluateResult {
  score: number;
  correct: boolean;
  feedback: string;
}

export async function evaluateAnswer(payload: EvaluatePayload): Promise<EvaluateResult> {
  // Give explicit default for MVP
  const finalPayload = { user_id: 1, ...payload };
  const res = await fetch(`${API_BASE}/api/evaluate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(finalPayload),
  });

  if (!res.ok) {
    throw new Error("Failed to evaluate answer");
  }

  return res.json();
}

export interface UserStats {
  total_points: number;
  accuracy: number;
  quizzes_taken: number;
}

export async function getUserStats(userId: number): Promise<UserStats> {
  const res = await fetch(`${API_BASE}/api/stats/${userId}`);
  if (!res.ok) throw new Error("Failed to fetch user stats");
  return res.json();
}


